### ISSUE TITLE
Error en el ejercicio 10 de la práctica 3

### ISSUE THREAD

**Issue by neftalito** [MatiasGuaymas/AYED#1]
En la linea 39:
`resolver(h, camAct, camMax, max, valorTotal, nivel++);`

Por cómo funciona el postIncrement se va a enviar el valor de nivel y luego incrementar en 1. Se debería cambiar por alguna de las siguientes lineas:
- `resolver(h, camAct, camMax, max, valorTotal, nivel+1);`
- `resolver(h, camAct, camMax, max, valorTotal, ++nivel);`

Para lograr el objetivo de enviar el nivel con el incremento correspondiente

**Comment by neftalito** [comment]
Adjunto el link que marca la linea del error
[AYED/src/Practica3/Ejercicio10/ParcialArboles.java#L39](https://github.com/MatiasGuaymas/AYED/blob/fb7398d57c0c3f3a215bed585aad6edc98b689aa/Resoluciones/AYED/src/Practica3/Ejercicio10/ParcialArboles.java#L39)

**Comment by MatiasGuaymas** [comment]
Hola Neftalí, gracias por la correción, ya lo cambie. Saludos
